var MessageType = {
  'REACT_RUNERTIME_READY': 'REACT_RUNERTIME_READY',
  'REACT_COMPONENTS_DID_UPDATE': 'REACT_COMPONENTS_DID_UPDATE',
  'ENABLED_STATE_CHANGE': 'ENABLED_STATE_CHANGE',
};

module.exports = MessageType;
