sudo: false
install:
  - yarn
language: node_js
node_js:
  - '8'
script:
  - yarn run lint
  - yarn run typecheck
  - yarn run test
cache:
  yarn: true
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
